name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Validate Commit Messages
        if: github.event_name == 'pull_request'
        run: |
          # Get all commits in PR
          COMMITS=$(git log --pretty=format:"%s" origin/${{ github.base_ref }}..HEAD)
          
          echo "Validating commit messages..."
          echo "$COMMITS" | while read -r commit; do
            if [[ ! "$commit" =~ ^(feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert)(\(.*\))?!?:\ .+ ]]; then
              echo "❌ Invalid commit message: $commit"
              echo "Commit messages must follow Conventional Commits format:"
              echo "  <type>[optional scope]: <description>"
              echo ""
              echo "Types: feat, fix, docs, style, refactor, perf, test, build, ci, chore, revert"
              echo ""
              echo "Examples:"
              echo "  feat(picker): add drag threshold option"
              echo "  fix(pro): resolve chip rendering issue"
              echo "  docs: update README installation steps"
              exit 1
            fi
          done
          
          echo "✅ All commit messages are valid"

  build-free:
    name: Build Free Package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: packages/MuiMultiDateRangePicker/package-lock.json

      - name: Install Dependencies
        run: |
          cd packages/MuiMultiDateRangePicker
          npm ci

      - name: Build
        run: |
          cd packages/MuiMultiDateRangePicker
          npm run build

      - name: Check Build Output
        run: |
          cd packages/MuiMultiDateRangePicker
          if [ ! -f "dist/index.js" ]; then
            echo "❌ CJS build failed"
            exit 1
          fi
          if [ ! -f "dist/index.mjs" ]; then
            echo "❌ ESM build failed"
            exit 1
          fi
          if [ ! -f "dist/index.d.ts" ]; then
            echo "❌ Type definitions build failed"
            exit 1
          fi
          echo "✅ Build output verified"

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: free-package-dist
          path: packages/MuiMultiDateRangePicker/dist/
          retention-days: 7

  build-pro:
    name: Build Pro Package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: packages/MuiMultiDateRangePickerPro/package-lock.json

      - name: Install Dependencies
        run: |
          cd packages/MuiMultiDateRangePickerPro
          npm ci

      - name: Build
        run: |
          cd packages/MuiMultiDateRangePickerPro
          npm run build

      - name: Check Build Output
        run: |
          cd packages/MuiMultiDateRangePickerPro
          if [ ! -f "dist/index.js" ]; then
            echo "❌ CJS build failed"
            exit 1
          fi
          if [ ! -f "dist/index.mjs" ]; then
            echo "❌ ESM build failed"
            exit 1
          fi
          if [ ! -f "dist/index.d.ts" ]; then
            echo "❌ Type definitions build failed"
            exit 1
          fi
          echo "✅ Build output verified"

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pro-package-dist
          path: packages/MuiMultiDateRangePickerPro/dist/
          retention-days: 7

  lint:
    name: Lint & Type Check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: [MuiMultiDateRangePicker, MuiMultiDateRangePickerPro]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: |
          cd packages/${{ matrix.package }}
          npm ci

      - name: Type Check
        run: |
          cd packages/${{ matrix.package }}
          npx tsc --noEmit

  summary:
    name: CI Summary
    needs: [validate, build-free, build-pro, lint]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Check Results
        run: |
          if [ "${{ needs.validate.result }}" != "success" ] || \
             [ "${{ needs.build-free.result }}" != "success" ] || \
             [ "${{ needs.build-pro.result }}" != "success" ] || \
             [ "${{ needs.lint.result }}" != "success" ]; then
            echo "❌ CI checks failed"
            exit 1
          fi
          echo "✅ All CI checks passed"

