name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Info Message
        if: github.event_name == 'pull_request'
        run: |
          echo "ℹ️  Individual commit messages are NOT validated"
          echo "ℹ️  Only the PR title needs to follow conventional format"
          echo "ℹ️  When you squash merge, the PR title becomes the commit message"
          echo ""
          echo "✅ Validation skipped - develop freely!"

  build-free:
    name: Build Free Package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: packages/MuiMultiDateRangePicker/package-lock.json

      - name: Install Dependencies
        run: |
          cd packages/MuiMultiDateRangePicker
          npm ci

      - name: Build
        run: |
          cd packages/MuiMultiDateRangePicker
          npm run build

      - name: Check Build Output
        run: |
          cd packages/MuiMultiDateRangePicker
          if [ ! -f "dist/index.js" ]; then
            echo "❌ CJS build failed"
            exit 1
          fi
          if [ ! -f "dist/index.mjs" ]; then
            echo "❌ ESM build failed"
            exit 1
          fi
          if [ ! -f "dist/index.d.ts" ]; then
            echo "❌ Type definitions build failed"
            exit 1
          fi
          echo "✅ Build output verified"

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: free-package-dist
          path: packages/MuiMultiDateRangePicker/dist/
          retention-days: 7

  build-pro:
    name: Build Pro Package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: packages/MuiMultiDateRangePickerPro/package-lock.json

      - name: Install Dependencies
        run: |
          cd packages/MuiMultiDateRangePickerPro
          npm ci

      - name: Build
        run: |
          cd packages/MuiMultiDateRangePickerPro
          npm run build

      - name: Check Build Output
        run: |
          cd packages/MuiMultiDateRangePickerPro
          if [ ! -f "dist/index.js" ]; then
            echo "❌ CJS build failed"
            exit 1
          fi
          if [ ! -f "dist/index.mjs" ]; then
            echo "❌ ESM build failed"
            exit 1
          fi
          if [ ! -f "dist/index.d.ts" ]; then
            echo "❌ Type definitions build failed"
            exit 1
          fi
          echo "✅ Build output verified"

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pro-package-dist
          path: packages/MuiMultiDateRangePickerPro/dist/
          retention-days: 7

  lint:
    name: Lint & Type Check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: [MuiMultiDateRangePicker, MuiMultiDateRangePickerPro]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: |
          cd packages/${{ matrix.package }}
          npm ci

      - name: Type Check
        run: |
          cd packages/${{ matrix.package }}
          npx tsc --noEmit

  summary:
    name: CI Summary
    needs: [build-free, build-pro, lint]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Check Results
        run: |
          if [ "${{ needs.build-free.result }}" != "success" ] || \
             [ "${{ needs.build-pro.result }}" != "success" ] || \
             [ "${{ needs.lint.result }}" != "success" ]; then
            echo "❌ CI checks failed"
            exit 1
          fi
          echo "✅ All CI checks passed"

