name: Main

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  check:
    name: Check if Release Needed
    runs-on: ubuntu-latest
    outputs:
      should_release: ${{ steps.check.outputs.should_release }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Check Commit Message
        id: check
        run: |
          MSG=$(git log -1 --pretty=%B)
          if [[ "$MSG" == chore:*release* ]]; then
            echo "should_release=false" >> $GITHUB_OUTPUT
            echo "Skipping - this is a release commit"
          else
            echo "should_release=true" >> $GITHUB_OUTPUT
          fi

  release:
    name: Release Packages
    needs: check
    if: needs.check.outputs.should_release == 'true'
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.publish.outputs.version }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Bump & Publish
        id: publish
        run: |
          set -e  # Exit on any error
          MSG=$(git log -1 --pretty=%B)
          
          # Determine bump type
          if echo "$MSG" | grep -qE "^feat.*!:|BREAKING CHANGE:"; then
            BUMP="major"
          elif echo "$MSG" | grep -qE "^feat(\(|:)"; then
            BUMP="minor"
          else
            BUMP="patch"
          fi
          
          # Get current version from pro package (use as source of truth)
          LATEST=$(npm view @spacedevin/react-mui-pro-multi-range-picker version 2>/dev/null || echo "0.0.0")
          IFS='.' read -r M N P <<< "$LATEST"
          case $BUMP in
            major) VER="$((M + 1)).0.0" ;;
            minor) VER="$M.$((N + 1)).0" ;;
            patch) VER="$M.$N.$((P + 1))" ;;
          esac
          
          echo "version=$VER" >> $GITHUB_OUTPUT
          echo "Publishing both packages at version: $VER (from $LATEST, bump: $BUMP)"
          
          # Free Package
          cd packages/MuiMultiDateRangePicker
          npm ci
          npm version $VER --no-git-tag-version
          npm run build
          npm publish --access public
          
          # Pro Package
          cd ../MuiMultiDateRangePickerPro
          npm ci
          npm version $VER --no-git-tag-version
          npm run build
          npm publish --access public
          
          # Commit and tag
          cd ../..
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add packages/*/package*.json
          git commit -m "chore: release v$VER"
          git tag -a "v$VER" -m "Release v$VER"
          git push origin main --follow-tags
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create GitHub Release
        if: success()
        run: |
          VER="${{ steps.publish.outputs.version }}"
          
          gh release create "v$VER" \
            --title "v$VER" \
            --notes "**Packages Released:**
          
          - \`@spacedevin/react-mui-multi-range-picker@$VER\`
          - \`@spacedevin/react-mui-pro-multi-range-picker@$VER\`
          
          Published to NPM" \
            --latest
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy-pages:
    name: Deploy to GitHub Pages
    needs: release
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Build Demo Pages
        run: |
          # Build ESM demo (Vite)
          cd examples/esm
          rm -rf node_modules package-lock.json
          npm install
          npm run build
          
          # Build CJS demo (Webpack)
          cd ../cjs
          rm -rf node_modules package-lock.json
          npm install
          npm run build
          
          # Create gh-pages directory structure
          cd ../..
          mkdir -p gh-pages/esm gh-pages/cjs
          
          # Copy demos
          cp -r examples/esm/dist/* gh-pages/esm/
          cp -r examples/cjs/dist/* gh-pages/cjs/
          
          # Create landing page
          cat > gh-pages/index.html << 'EOF'
          <!DOCTYPE html>
          <html>
          <head>
            <title>MUI Multi Range Date Picker</title>
            <meta charset="UTF-8" />
            <meta name="viewport" content="width=device-width, initial-scale=1.0" />
            <style>
              body { 
                font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, sans-serif;
                max-width: 900px; 
                margin: 50px auto; 
                padding: 20px;
                line-height: 1.6;
              }
              h1 { 
                color: #1976d2;
                font-size: 2.5em;
                margin-bottom: 0.5em;
              }
              .description {
                font-size: 1.1em;
                color: #555;
                margin-bottom: 2em;
              }
              .demo-links { 
                display: grid;
                grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
                gap: 20px;
                margin-top: 30px;
              }
              .demo-link { 
                padding: 30px; 
                border: 2px solid #1976d2; 
                border-radius: 12px; 
                text-decoration: none; 
                color: #1976d2;
                text-align: center;
                transition: all 0.3s ease;
                background: white;
              }
              .demo-link:hover { 
                background: #e3f2fd;
                transform: translateY(-2px);
                box-shadow: 0 4px 12px rgba(25, 118, 210, 0.2);
              }
              .demo-link h3 {
                margin-top: 0;
                font-size: 1.5em;
              }
              .demo-link p {
                margin: 0;
                color: #666;
              }
              .badge {
                display: inline-block;
                padding: 4px 12px;
                border-radius: 12px;
                font-size: 0.8em;
                font-weight: 600;
                margin-top: 10px;
              }
              .badge-esm {
                background: #4caf50;
                color: white;
              }
              .badge-cjs {
                background: #ff9800;
                color: white;
              }
              .npm-links {
                margin-top: 3em;
                padding: 20px;
                background: #f5f5f5;
                border-radius: 8px;
              }
              .npm-links h3 {
                margin-top: 0;
              }
              .npm-links a {
                color: #1976d2;
                text-decoration: none;
              }
              .npm-links a:hover {
                text-decoration: underline;
              }
            </style>
          </head>
          <body>
            <h1>🗓️ MUI Multi Range Date Picker</h1>
            <p class="description">
              Interactive demos showcasing ESM and CommonJS builds. Both demos pull from NPM to validate the published packages.
            </p>
            
            <div class="demo-links">
              <a href="./esm/" class="demo-link">
                <h3>ESM Demo</h3>
                <p>Modern ES Modules build with Vite</p>
                <span class="badge badge-esm">ES Modules</span>
              </a>
              <a href="./cjs/" class="demo-link">
                <h3>CJS Demo</h3>
                <p>CommonJS build with Webpack</p>
                <span class="badge badge-cjs">CommonJS</span>
              </a>
            </div>

            <div class="npm-links">
              <h3>📦 NPM Packages</h3>
              <p>
                <strong>Free:</strong> <a href="https://www.npmjs.com/package/@spacedevin/react-mui-multi-range-picker" target="_blank">@spacedevin/react-mui-multi-range-picker</a><br>
                <strong>Pro:</strong> <a href="https://www.npmjs.com/package/@spacedevin/react-mui-pro-multi-range-picker" target="_blank">@spacedevin/react-mui-pro-multi-range-picker</a>
              </p>
            </div>
          </body>
          </html>
          EOF

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'gh-pages'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
